"""First

Revision ID: 18312370d8ad
Revises: 
Create Date: 2022-02-25 14:53:08.038255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18312370d8ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
