"""Fourth?

Revision ID: 3aff9995946a
Revises: aae920a2432a
Create Date: 2022-02-27 19:33:40.846845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aff9995946a'
down_revision = 'aae920a2432a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
