"""Added all cascade deletions

Revision ID: 49069bc285be
Revises: cace551312e7
Create Date: 2022-03-01 16:37:32.735128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49069bc285be'
down_revision = 'cace551312e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
