"""Third

Revision ID: aae920a2432a
Revises: 7794272b6294
Create Date: 2022-02-27 16:04:22.081099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae920a2432a'
down_revision = '7794272b6294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_owner_id'), 'owner', ['id'], unique=True)
    op.add_column('Car', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Car', 'owner', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Car', type_='foreignkey')
    op.drop_column('Car', 'owner')
    op.drop_index(op.f('ix_owner_id'), table_name='owner')
    op.drop_table('owner')
    # ### end Alembic commands ###
