"""added user

Revision ID: b7706313cb1c
Revises: 1302f65c8d7a
Create Date: 2022-02-28 16:31:39.548708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7706313cb1c'
down_revision = '1302f65c8d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
