"""Added user

Revision ID: c6023c0875c4
Revises: b7706313cb1c
Create Date: 2022-03-01 12:36:20.253608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6023c0875c4'
down_revision = 'b7706313cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
