"""added cascade

Revision ID: cace551312e7
Revises: 9b009ecbc93c
Create Date: 2022-03-01 16:04:36.860409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cace551312e7'
down_revision = '9b009ecbc93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_manager_fkey', 'car', type_='foreignkey')
    op.drop_constraint('car_owner_fkey', 'car', type_='foreignkey')
    op.create_foreign_key(None, 'car', 'owner', ['owner'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'car', 'manager', ['manager'], ['id'], ondelete='CASCADE')
    op.drop_constraint('insurancelist_car_fkey', 'insurancelist', type_='foreignkey')
    op.drop_constraint('insurancelist_insurance_fkey', 'insurancelist', type_='foreignkey')
    op.create_foreign_key(None, 'insurancelist', 'car', ['car'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insurancelist', 'insurance', ['insurance'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insurancelist', type_='foreignkey')
    op.drop_constraint(None, 'insurancelist', type_='foreignkey')
    op.create_foreign_key('insurancelist_insurance_fkey', 'insurancelist', 'insurance', ['insurance'], ['id'])
    op.create_foreign_key('insurancelist_car_fkey', 'insurancelist', 'car', ['car'], ['id'])
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.create_foreign_key('car_owner_fkey', 'car', 'owner', ['owner'], ['id'])
    op.create_foreign_key('car_manager_fkey', 'car', 'manager', ['manager'], ['id'])
    # ### end Alembic commands ###
